# Generated by Django 4.2.7 on 2026-01-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfuquiz',
            name='questions',
            field=models.JSONField(help_text='List of quiz questions with options'),
        ),
    ]
